### ISSUE TITLE
Sitemap.xml

### ISSUE THREAD

**Issue by GioviQ** [JadeX/Orchard.HtmlMinifier#1]
I had to add /sitemap.xml to exclusions beacause minifier breaks the format.

**Comment by Xeevis** [comment]
Hi GioviQ,
XML is supported format by the minifier along with HTML and XHTML and should be working. I need to see source markup for `sitemap.xml` minifier is working with and how it looks like broken to better understand the issue. Thank you.

**Comment by GioviQ** [comment]
`<urlset xmlns=http://www.sitemaps.org/schemas/sitemap/0.9><url><loc>http://risparmio.dindini.it/ascensore-meglio-le-scale</loc><changefreq>weekly</changefreq><lastmod>2015-05-06</lastmod><priority>0.5</priority></url><url><loc>http://risparmio.dindini.it/cambio-operatore-telefonico</loc><changefreq>weekly</changefreq><lastmod>2015-05-19</lastmod><priority>0.5</priority></url><url><loc>http://risparmio.dindini.it/chiudi-il-rubinetto-quando-non-ti-serve</loc><changefreq>weekly</changefreq><lastmod>2015-05-17</lastmod><priority>0.5</priority></url><url><loc>http://risparmio.dindini.it/come-risparmiare-acqua-mentre-fai-la-doccia</loc><changefreq>weekly</changefreq><lastmod>2015-05-17</lastmod><priority>0.5</priority></url><url><loc>http://risparmio.dindini.it/come-risparmiare-benzina-con-lo-stile-di-guida</loc><changefreq>weekly</changefreq><lastmod>2015-05-03</lastmod><priority>0.5</priority></url><url><loc>http://risparmio.dindini.it/come-risparmiare-carburante-facendo-il-pieno</loc><changefreq>weekly</changefreq><lastmod>2015-05-16</lastmod><priority>0.5</priority></url><url><loc>http://risparmio.dindini.it/come-risparmiare-energia-elettrica-con-le-lampadine-a-led</loc><changefreq>weekly</changefreq><lastmod>2015-05-19</lastmod><priority>0.5</priority></url><url><loc>http://risparmio.dindini.it/come-risparmiare-sull-anticalcare</loc><changefreq>weekly</changefreq><lastmod>2015-05-04</lastmod><priority>0.5</priority></url><url><loc>http://risparmio.dindini.it/risparmia-corrente-spegni-tutto-standby-mai-piu</loc><changefreq>weekly</changefreq><lastmod>2015-05-13</lastmod><priority>0.5</priority></url><url><loc>http://risparmio.dindini.it/risparmiare-corrente-con-l-aspirapolvere</loc><changefreq>weekly</changefreq><lastmod>2015-05-19</lastmod><priority>0.5</priority></url></urlset>`

That's what Chrome says:
This page contains the following errors:

error on line 1 at column 15: AttValue: " or ' expected
Below is a rendering of the page up to the first error.
